version: '3'

services:
  joba:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 80:8080
    networks:
      - base-network

networks:
  base-network:
    driver: bridge

volumes:
  node_modules:
