export const english = {
  "total": 2,
  "jobs": [
    {
      "_index": "english",
      "_type": "doc",
      "_id": "30938491",
      "source": {
        "jobs_id": "30938491",
        "noc_2011": "6321",
        "skill_level": "B",
        "remote_cd": "1271873",
        "title": "chef",
        "noc": "6321",
        "work_period_cd": "F",
        "employer_type_id": "0",
        "edulevel_cd": "C",
        "wage_class": "D",
        "postal_code": "L9L1P9",
        "employer_id": "36894",
        "lang": "en",
        "skill_categories": [
          null
        ],
        "job_source_id": "16",
        "work_term_cd": "P",
        "work_lang_cd": "E",
        "app_methods": [
          null
        ],
        "naics_id": "37",
        "hours": "37.5 hours per week",
        "employer_name_case": "Hyland Family Restaurant",
        "employer_name_string": "Hyland Family Restaurant",
        "num_positions": "1",
        "job_senior_flag": "true",
        "various_location_flag": "false",
        "job_student_flag": "true",
        "job_youth_flag": "true",
        "job_apprentice_flag": "true",
        "job_disability_flag": "true",
        "job_aboriginal_flag": "true",
        "program_title": "false",
        "job_vismin_flag": "true",
        "job_newcomer_flag": "true",
        "job_veteran_flag": "true",
        "latlng_variance": "1",
        "los_id": "2",
        "postal_code_ind": "1",
        "experience_min": "24",
        "date_posted": "2019-07-30T10:59:00Z",
        "file_update_date": "2019-07-30T09:56:00Z",
        "import_date": "2019-07-30T10:04:43Z",
        "display_until": "2019-08-29T23:59:00Z",
        "salary_hourly": "24.0",
        "salary_weekly": "900.0",
        "work_hours": "37.5",
        "city_name": "Port Perry",
        "lmi_geoarea_cd": "9219",
        "url": "https://www.jobbank.gc.ca/jobsearch/jobposting/30938491",
        "latlng": "44.100631,-78.939918",
        "latlng_rpt": "44.100631,-78.939918",
        "city_id": "23372",
        "noc_jobtitle_concordance_id": "16420",
        "major_city_id": "23372",
        "employment_terms": [
          null
        ],
        "province_cd": "ON",
        "salary": "$24.00 hourly",
        "employer_name": "Hyland Family Restaurant"
      }
    },
    {
      "_index": "english",
      "_type": "doc",
      "_id": "30938492",
      "source": {
        "jobs_id": "30938492",
        "noc_2011": "6321",
        "skill_level": "B",
        "remote_cd": "1271873",
        "title": "dishwasher",
        "noc": "6321",
        "work_period_cd": "F",
        "employer_type_id": "0",
        "edulevel_cd": "C",
        "wage_class": "D",
        "postal_code": "L9L1P9",
        "employer_id": "36894",
        "lang": "en",
        "skill_categories": [
          null
        ],
        "job_source_id": "16",
        "work_term_cd": "P",
        "work_lang_cd": "E",
        "app_methods": [
          null
        ],
        "naics_id": "37",
        "hours": "37.5 hours per week",
        "employer_name_case": "Hyland Family Restaurant",
        "employer_name_string": "Hyland Family Restaurant",
        "num_positions": "1",
        "job_senior_flag": "true",
        "various_location_flag": "false",
        "job_student_flag": "true",
        "job_youth_flag": "true",
        "job_apprentice_flag": "true",
        "job_disability_flag": "true",
        "job_aboriginal_flag": "true",
        "program_title": "false",
        "job_vismin_flag": "true",
        "job_newcomer_flag": "true",
        "job_veteran_flag": "true",
        "latlng_variance": "1",
        "los_id": "2",
        "postal_code_ind": "1",
        "experience_min": "24",
        "date_posted": "2019-07-10T10:59:00Z",
        "file_update_date": "2019-07-30T09:56:00Z",
        "import_date": "2019-07-30T10:04:43Z",
        "display_until": "2019-08-29T23:59:00Z",
        "salary_hourly": "24.0",
        "salary_weekly": "900.0",
        "work_hours": "37.5",
        "city_name": "Toronto",
        "lmi_geoarea_cd": "9219",
        "url": "https://www.jobbank.gc.ca/jobsearch/jobposting/30938491",
        "latlng": "44.100631,-78.939918",
        "latlng_rpt": "44.100631,-78.939918",
        "city_id": "23372",
        "noc_jobtitle_concordance_id": "16420",
        "major_city_id": "23372",
        "employment_terms": [
          null
        ],
        "province_cd": "ON",
        "salary": "24.00 hourly",
        "employer_name": "Cows Restaurant"
      }
    }
  ]
};
  
export const french = {
  "total": 2,
  "jobs": [
    {
      "_index": "french",
      "_type": "doc",
      "_id": "30938493",
      "source": {
        "jobs_id": "30938493",
        "noc_2011": "6321",
        "skill_level": "B",
        "remote_cd": "1271873",
        "title": "Cuisineur",
        "noc": "6321",
        "work_period_cd": "F",
        "employer_type_id": "0",
        "edulevel_cd": "C",
        "wage_class": "D",
        "postal_code": "L9L1P9",
        "employer_id": "36894",
        "lang": "en",
        "skill_categories": [
          null
        ],
        "job_source_id": "16",
        "work_term_cd": "P",
        "work_lang_cd": "E",
        "app_methods": [
          null
        ],
        "naics_id": "37",
        "hours": "37.5 hours per week",
        "employer_name_case": "Hyland Family Restaurant",
        "employer_name_string": "Hyland Family Restaurant",
        "num_positions": "1",
        "job_senior_flag": "true",
        "various_location_flag": "false",
        "job_student_flag": "true",
        "job_youth_flag": "true",
        "job_apprentice_flag": "true",
        "job_disability_flag": "true",
        "job_aboriginal_flag": "true",
        "program_title": "false",
        "job_vismin_flag": "true",
        "job_newcomer_flag": "true",
        "job_veteran_flag": "true",
        "latlng_variance": "1",
        "los_id": "2",
        "postal_code_ind": "1",
        "experience_min": "24",
        "date_posted": "2019-07-30T10:59:00Z",
        "file_update_date": "2019-07-30T09:56:00Z",
        "import_date": "2019-07-30T10:04:43Z",
        "display_until": "2019-08-29T23:59:00Z",
        "salary_hourly": "24.0",
        "salary_weekly": "900.0",
        "work_hours": "37.5",
        "city_name": "Port Perry",
        "lmi_geoarea_cd": "9219",
        "url": "https://www.jobbank.gc.ca/jobsearch/jobposting/30938491",
        "latlng": "44.100631,-78.939918",
        "latlng_rpt": "44.100631,-78.939918",
        "city_id": "23372",
        "noc_jobtitle_concordance_id": "16420",
        "major_city_id": "23372",
        "employment_terms": [
          null
        ],
        "province_cd": "ON",
        "salary": "24.00$ par heure",
        "employer_name": "Restaurant de famille Hyland"
      }
    },
    {
      "_index": "french",
      "_type": "doc",
      "_id": "30938494",
      "source": {
        "jobs_id": "30938494",
        "noc_2011": "6321",
        "skill_level": "B",
        "remote_cd": "1271873",
        "title": "laveur",
        "noc": "6321",
        "work_period_cd": "F",
        "employer_type_id": "0",
        "edulevel_cd": "C",
        "wage_class": "D",
        "postal_code": "L9L1P9",
        "employer_id": "36894",
        "lang": "en",
        "skill_categories": [
          null
        ],
        "job_source_id": "16",
        "work_term_cd": "P",
        "work_lang_cd": "E",
        "app_methods": [
          null
        ],
        "naics_id": "37",
        "hours": "37.5 hours per week",
        "employer_name_case": "Hyland Family Restaurant",
        "employer_name_string": "Hyland Family Restaurant",
        "num_positions": "1",
        "job_senior_flag": "true",
        "various_location_flag": "false",
        "job_student_flag": "true",
        "job_youth_flag": "true",
        "job_apprentice_flag": "true",
        "job_disability_flag": "true",
        "job_aboriginal_flag": "true",
        "program_title": "false",
        "job_vismin_flag": "true",
        "job_newcomer_flag": "true",
        "job_veteran_flag": "true",
        "latlng_variance": "1",
        "los_id": "2",
        "postal_code_ind": "1",
        "experience_min": "24",
        "date_posted": "2019-07-10T10:59:00Z",
        "file_update_date": "2019-07-30T09:56:00Z",
        "import_date": "2019-07-30T10:04:43Z",
        "display_until": "2019-08-29T23:59:00Z",
        "salary_hourly": "24.0",
        "salary_weekly": "900.0",
        "work_hours": "37.5",
        "city_name": "Toronto",
        "lmi_geoarea_cd": "9219",
        "url": "https://www.jobbank.gc.ca/jobsearch/jobposting/30938491",
        "latlng": "44.100631,-78.939918",
        "latlng_rpt": "44.100631,-78.939918",
        "city_id": "23372",
        "noc_jobtitle_concordance_id": "16420",
        "major_city_id": "23372",
        "employment_terms": [
          null
        ],
        "province_cd": "ON",
        "salary": "24.00 par heure",
        "employer_name": "Restaurant de Vache"
      }
    }
  ]
};
